// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.mvc.models.Layout' );
goog.provide( 'zz.mvc.models.LayoutDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );

goog.require( 'zz.mvc.models.View' );


/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.mvc.models.LayoutDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.width = undefined;

    /**
     * @type {string}
     */
    this.height = undefined;

    /**
     * @type {zz.mvc.models.View}
     */
    this.views = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.mvc.models.LayoutDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.mvc.models.Layout = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.mvc.models.Layout, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.mvc.models.LayoutDatarow}
*/
zz.mvc.models.Layout.prototype.DatarowConstructor = zz.mvc.models.LayoutDatarow;

/**
* Return zz.mvc.models.LayoutDatarow schema object.
* @override
* @returns {Object}
*/
zz.mvc.models.Layout.prototype.getDatarowSchema = function( ){

return {
        width: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        height: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        views: {
                index: 2,
                type: zz.mvc.models.View,
                required: false
        }
};
};